"""
HydroGuard-AI: Layer 5 — GIS Export Tools

Automated generation of KML and Shapefile exports for
NDRF/SDRF/HADR dispatch and Google Earth visualization.
"""

import os
import json
from datetime import datetime, timezone
from typing import Optional

import simplekml


# Risk color mapping for KML
KML_COLORS = {
    "IMMINENT": simplekml.Color.red,
    "WARNING":  simplekml.Color.orange,
    "WATCH":    simplekml.Color.yellow,
    "NORMAL":   simplekml.Color.green,
}


def export_alert_kml(
    dam_name: str,
    lat: float,
    lon: float,
    probability: float,
    alert_level: str = "WARNING",
    explanation: str = "",
    output_path: str = "exports/alert.kml",
) -> str:
    """
    Export a dam breach alert as a KML file for Google Earth.

    Args:
        dam_name: Name of the at-risk dam
        lat: Latitude of the dam
        lon: Longitude of the dam
        probability: Breach probability P(breach)
        alert_level: Alert classification (NORMAL/WATCH/WARNING/IMMINENT)
        explanation: SHAP-based explanation text
        output_path: Output KML file path

    Returns:
        Path to the generated KML file
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    kml = simplekml.Kml(name=f"HydroGuard-AI Alert: {dam_name}")

    # Document description
    kml.document.description = (
        f"Automated Dam Breach Risk Alert\n"
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        f"System: HydroGuard-AI v1.0"
    )

    # Add alert point
    color = KML_COLORS.get(alert_level, simplekml.Color.white)

    pnt = kml.newpoint(
        name=f"⚠️ {dam_name} — P(Breach): {probability*100:.1f}%"
    )
    pnt.coords = [(lon, lat)]
    pnt.style.iconstyle.color = color
    pnt.style.iconstyle.scale = 1.5
    pnt.style.labelstyle.scale = 1.2

    # Rich description with HTML
    pnt.description = f"""
    <![CDATA[
    <h2 style="color:{'red' if alert_level == 'IMMINENT' else 'orange'}">
        {alert_level} ALERT — {dam_name}
    </h2>
    <table border="1" cellpadding="5">
        <tr><td><b>Breach Probability</b></td><td>{probability*100:.1f}%</td></tr>
        <tr><td><b>Alert Level</b></td><td>{alert_level}</td></tr>
        <tr><td><b>Coordinates</b></td><td>{lat:.4f}°N, {lon:.4f}°E</td></tr>
        <tr><td><b>Generated</b></td><td>{datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}</td></tr>
    </table>
    <p><b>Risk Explanation:</b> {explanation or 'See SHAP analysis in dashboard'}</p>
    <p><i>Generated by HydroGuard-AI Automated Surveillance System</i></p>
    ]]>
    """

    # Add danger zone circle (approximate)
    if probability >= 0.50:
        # Create a rough circular polygon (~5km radius for high risk)
        radius_deg = 0.05 if probability >= 0.75 else 0.03
        circle_coords = []
        import math
        for angle in range(0, 361, 10):
            clat = lat + radius_deg * math.cos(math.radians(angle))
            clon = lon + radius_deg * math.sin(math.radians(angle))
            circle_coords.append((clon, clat))

        danger_zone = kml.newpolygon(
            name=f"Danger Zone — {dam_name}",
            outerboundaryis=circle_coords,
        )
        danger_zone.style.polystyle.color = simplekml.Color.changealphaint(
            80, color
        )
        danger_zone.style.linestyle.color = color
        danger_zone.style.linestyle.width = 2

    kml.save(output_path)
    print(f"[EXPORT] 📍 KML alert exported: {output_path}")
    return output_path


def export_multi_dam_kml(
    dam_results: list,
    output_path: str = "exports/hydroguard_alerts.kml",
) -> str:
    """
    Export multiple dam alerts as a single KML file.

    Args:
        dam_results: List of dicts with keys:
            name, lat, lon, probability, alert_level, explanation
        output_path: Output KML file path

    Returns:
        Path to the generated KML file
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    kml = simplekml.Kml(name="HydroGuard-AI — Multi-Dam Risk Assessment")
    kml.document.description = (
        f"Automated Multi-Dam Breach Risk Assessment\n"
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}\n"
        f"Total Dams Assessed: {len(dam_results)}"
    )

    # Create folders by alert level
    folders = {
        "IMMINENT": kml.newfolder(name="🔴 IMMINENT FAILURE"),
        "WARNING":  kml.newfolder(name="🟠 WARNING"),
        "WATCH":    kml.newfolder(name="🟡 WATCH"),
        "NORMAL":   kml.newfolder(name="🟢 NORMAL"),
    }

    for dam in dam_results:
        level = dam.get("alert_level", "NORMAL")
        folder = folders.get(level, folders["NORMAL"])
        color = KML_COLORS.get(level, simplekml.Color.white)

        pnt = folder.newpoint(
            name=f"{dam['name']} — {dam['probability']*100:.1f}%"
        )
        pnt.coords = [(dam["lon"], dam["lat"])]
        pnt.style.iconstyle.color = color
        pnt.style.iconstyle.scale = 1.2

        pnt.description = (
            f"P(Breach): {dam['probability']*100:.1f}% | "
            f"Alert: {level} | "
            f"Explanation: {dam.get('explanation', 'N/A')}"
        )

    kml.save(output_path)
    print(f"[EXPORT] 📍 Multi-dam KML exported: {output_path} ({len(dam_results)} dams)")
    return output_path


def export_alert_json(
    dam_results: list,
    output_path: str = "exports/alert_payload.json",
) -> str:
    """
    Export alert data as JSON payload for webhook dispatch.

    Args:
        dam_results: List of dam result dictionaries
        output_path: Output JSON file path

    Returns:
        Path to the generated JSON file
    """
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    payload = {
        "system": "HydroGuard-AI",
        "version": "1.0.0",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_dams_assessed": len(dam_results),
        "critical_alerts": sum(
            1 for d in dam_results
            if d.get("alert_level") in ("IMMINENT", "WARNING")
        ),
        "alerts": dam_results,
    }

    with open(output_path, "w") as f:
        json.dump(payload, f, indent=2, default=str)

    print(f"[EXPORT] 📄 JSON payload exported: {output_path}")
    return output_path


def export_full_report(
    dam_results: list,
    output_dir: str = "exports",
) -> dict:
    """
    Generate complete export package: KML + JSON.

    Returns dict of generated file paths.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    os.makedirs(output_dir, exist_ok=True)

    paths = {
        "kml": export_multi_dam_kml(
            dam_results,
            os.path.join(output_dir, f"hydroguard_{timestamp}.kml"),
        ),
        "json": export_alert_json(
            dam_results,
            os.path.join(output_dir, f"hydroguard_{timestamp}.json"),
        ),
    }

    print(f"\n[EXPORT] ✅ Full report generated in {output_dir}/")
    return paths
